data:
  csv_file_path: ./imdb-dataset.csv
  test_set_ratio: 0.3
  train_csv_save_path: ./train.csv
  test_csv_save_path: ./test.csv

features:
  vectorizer: tfidf-vectorizer
  train_features_save_path: ./train.joblib
  test_features_save_path: ./test.joblib

train:
  penalty: l2
  C: 1.0
  solver: lbfgs
  model_save_path: ./model.joblib

evaluate:
  metric: accuracy
  results_save_path: ./results.yaml